import PDFRoutes from "./pdf-for-frontend.js";
import MainCategoryCategorySubCategoryRoutes from "./maincategory-category-subcategory.js";
import QuoteRoutes from "./quote-request.js";
import PrepareQuoteRoutes from "./prepare-quote-by-seller.js";
import SubmitQuoteRoutes from "./submit-quote-by-seller.js";
import UpdateVenderStatusRoutes from "./update-vender-status.js";
import CartRoutes from "./cart-by-school.js";
import OrderFromBuyerRoutes from "./order-from-buyer.js";
import QuoteProposalRoutes from "./quote-proposal.js";
import OrderDetailsFromSellerRoutes from "./order-details-from-seller.js";
import OrderProgressStatusRoutes from "./order-progress-status.js";
import UpdateTDSRoutes from "./update-tds.js";
import CancelOrder from "./order-cancel.js";
import FeedBackAndRating from "./feedback-and-rating.js";

export default (app) => {
  app.use("/api", MainCategoryCategorySubCategoryRoutes);
  app.use("/api", QuoteRoutes);
  app.use("/api", PrepareQuoteRoutes);
  app.use("/api", SubmitQuoteRoutes);
  app.use("/api", UpdateVenderStatusRoutes);
  app.use("/api", CartRoutes);
  app.use("/api", OrderFromBuyerRoutes);
  app.use("/api", QuoteProposalRoutes);
  app.use("/api", OrderDetailsFromSellerRoutes);
  app.use("/api", OrderProgressStatusRoutes);
  app.use("/api", UpdateTDSRoutes);
  app.use("/api", CancelOrder);
  app.use("/api", FeedBackAndRating);
};
